### ISSUE TITLE
[1]Footer not working correctly when resizing.

### ISSUE THREAD

**Issue by Dominent** [KurtBit/Galicia-Website-Project#1]
Content does not fill the container as it is supposed to do, elements are overlapping.
Occurs at 900 px to 275 px resize !

**Comment by IvoryTailor** [comment]
[image: Вградено изображение 1]

2016-08-20 21:55 GMT+03:00 Petromil Pavlov notifications@github.com:

**Comment by Dominent** [comment]
I meant 900px width till 275px width !

**Comment by Dominent** [comment]
Issue fixed
