### ISSUE TITLE
Captcha is not responsive.

### ISSUE THREAD

**Issue by IvoryTailor** [KurtBit/Galicia-Website-Project#7]
I have noticed that the captcha is not aligning properly when resizing the window.

**Comment by IvoryTailor** [comment]
I think it is done now. 
@Dominent please check.

* [XS Display](http://prntscr.com/ezgmv7)
* [S Display](http://prntscr.com/ezgnku)
* [Md Display](http://prntscr.com/ezgo20)
* [Lg Display](http://prntscr.com/ezgo8c)

**Comment by Dominent** [comment]
Images look good.
Open a pull request to review code.

**Comment by IvoryTailor** [comment]
@Dominent, here it is: https://github.com/KurtBit/Galicia-Website-Project/commit/fc2982a9605155f1a0bc5972461797bc07262cf0

**Comment by Dominent** [comment]
Closed
